name: 'Android CI'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: 'Kotlin Unit Tests'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: 'Android Unit Tests'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest
